server:
  port: 8080
  servlet:
    context-path: /ipa
spring:
  datasource:
    url: jdbc:mysql://140.143.206.106:3306/ipa
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 140.143.206.106:9300