server:
  port: 8088
#  servlet:
#    context-path: /ipa
spring:
  datasource:
    url: jdbc:mysql://140.143.206.106:3306/ipa
    username: root
    password: yang,guang.0
    driver-class-name: com.mysql.jdbc.Driver
