server:
  port: 8060
#  servlet:
#    context-path: /ipa
spring:
  datasource:
    url: jdbc:mysql://140.143.206.106:3306/ipa
    username: root
    password: yang,guang.0
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379


#logging:
#  level:
#    root: debug